spring:
  application:
    name: stockguard

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/stockguard}
    username: ${SPRING_DATASOURCE_USERNAME:stockguard}
    password: ${SPRING_DATASOURCE_PASSWORD:stockguard}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:127.0.0.1}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      ssl:
        enabled: ${SPRING_DATA_REDIS_SSL_ENABLED:false}

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:127.0.0.1}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    virtual-host: ${SPRING_RABBITMQ_VHOST:/}
    ssl:
      enabled: ${SPRING_RABBITMQ_SSL_ENABLED:false}

server:
  port: ${PORT:8080}