spring:
  application:
    name: stockguard

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/stockguard
    username: stockguard
    password: stockguard
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: 127.0.0.1
      port: 6379

server:
  port: 8080

aws:
  region: us-east-1
  sqs:
    queue-url: "REPLACE_ME"